### ISSUE TITLE
sh2proxy compatibility with SweetFX ?

### ISSUE THREAD

**Issue by TS88** [emoose/sh2proxy#2]
First of all I must congratulate you for this amazing work! It has worked brilliantly on all PC machines I've tested it, finally making SH2's PC port the smoothest and most beautiful version to play.

I wouldn't call this exactly a problem, but recently I've started to use the SweetFX injector to apply various visual tweaks to many games, such as color adjustments or SMAA. However, these injectors work only with games running on DX9 and above, meaning you need to use the "DX8 to DX9 converter" (=replacement file for d3d8.dll + d3d9.dll) on SH2 first. With the default SH2's files and manual affinity fix, I could easily tweak the looks so that the game's Noise effect doesn't wash out the visuals so hard,.
However since sh2proxy uses a customized d3d8.dll file, the SweetFX and any other injector compatibility is lost. 

My question / suggestion: would it be possible to edit the d3d8 file used in the sh2proxy to support SweetFX, somehow incorporating the adjustments of the DX8 converter's files?

**Comment by emoose** [comment]
I looked into it and seems I can make it hook a different DLL instead, we don't actually have to hook d3d8.dll since we don't change any DX stuff :smile:

I've made a build that hooks dinput8.dll, works fine for me but I haven't got SweetFX set up, can you try it out?

https://mega.co.nz/#!uF9yDAyA!NFCFCJM5KObT-RtPazleRzEbRna_z0qpzer5PrEh36o

**Comment by TS88** [comment]
Thanks for the response!

I gave the version a try. As expected, the game starts and works fine with the new proxy. However problems start to appear the moment I add the ENB's DX8 to DX9 convertor and SweetFX. No matter what kind of combinations of the files I tried, the result was either a straight crash to desktop with no error messages, or the "SH2.exe has stopped working", both at the launch. The latter gives following info:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	sh2pc.exe
  Application Version:	0.0.0.0
  Application Timestamp:	68373737
  Fault Module Name:	d3d8.dll
  Fault Module Version:	1.0.0.1
  Fault Module Timestamp:	4f17c975
  Exception Code:	c0000005
  Exception Offset:	000016ec
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1035
  Additional Information 1:	4032
  Additional Information 2:	4032958b1623adee6d69a6e09c88892d
  Additional Information 3:	1656
  Additional Information 4:	165686f6ea9758e6549670909bf3e626

The ENB Convertor adds a d3d8.dll file and enbconvertor.ini, which seems to work as an proxy of its own. It has the following settings:

[PROXY]
EnableProxyLibrary=1
InitProxyFunctions=1
ProxyLibrary=d3d9.dll

All this enables SweetFX and all the other injectors to actually work on the game, as they require the software to run on DX9.
By trial and error (=renaming files), I was once able to start the combination together, but this resulted ALL the game's models to disappear, leaving only gray fog and the SweetFX's effects visible.

**Comment by emoose** [comment]
Hmm that's strange, I managed to get it working fine (only tested up to getting the town map, but no CTDs up to then)

I used:
ENB DX8->DX9 v0036 (http://enbdev.com/convertor_dx8_dx9_v0036.htm)
SweetFX 1.5.1 (http://www.guru3d.com/files-get/sweetfx-shader-suite-download,1.html)
sh2proxy 0.2

Here's a pack of everything put together: https://mega.co.nz/#!HIERjRZT!UQAKoTwK1GIUpENZq-gzIFhy1hDWtXw-mSYe8_xxc54

Can you test with that? If it doesn't work for you then I guess it could be a driver/hardware problem, can you also attach your PC's specs if it still isn't working?

**Comment by jsatu9** [comment]
Hey emoose I'm having a problem with the install of the sh2proxy. I have tried following the install instructions but I am really confused and don't understand what the hell I'm supposed to do. So I was wondering would you bee able to make a short video of how to install it or even reply to this with more refined and detailed install instructions. Thanks for any help you provide :)

**Comment by TS88** [comment]
well I'm not him, but you only need to download the RELEASE version of sh2proxy from the front page. It has 3 files: new sh2pc.exe, d3d8.dll or d8input.dll depending the version you use, and file called sh2proxy.ini .

Drag and drop those to the game's install directory, and overwrite the old sh2pc.exe file. 
Open the sh2proxy.ini in a Notepad or any other text editor, and adjust the settings as you wish.

You're done!

**Comment by jsatu9** [comment]
Ohh haha thanks TS88 I downloaded the wrong one XD

**Comment by emoose** [comment]
That "has stopped working" thing is strange, I just installed DX8->DX9, SweetFX and sh2proxy 0.2 and it worked fine. Glad to see you got it working though, maybe you could post up a pack of the exes/dlls/inis you used in case others want to try it out.

The random "has stopped working" messages you get are weird too, mine launches fine each time I try, only time I heard of it crashing with others was when they used AMD cards (at least I think so, haven't heard anything back yet..).

Maybe it's an issue with some software you have installed? Because my specs are almost the exact same as yours but I don't get any problems.

I'll take look into the white texture issue too, saw someone posted on 4chan about it working fine with Intel cards, and the fog was fixed with Intel too, the poster assumed it was because newer cards can't draw it properly but I've got a feeling that SH2 is probably disabling something because it doesn't recognize the card. Too bad the thread was already archived by the time I saw it, would have been helpful if I could talk with them.

Anyway I'm going to close this issue now it seems that it's (sorta) fixed, I'll start a new one for the white texture stuff though

**Comment by TwelveCharzz** [comment]
MEGA links are dead, does anyone have a mirror?

**Comment by TS88** [comment]
I re-upped the stuff on mediafire now.

sh2proxy v0.1:
http://www.mediafire.com/download/a1tp97wxd86riy6/sh2proxy_0.1.zip

sh2proxy v0.2:
http://www.mediafire.com/download/ceq5igqwf98mgnm/sh2proxy-0.2.zip

enbconvertor dx8 to dx9:
http://www.mediafire.com/download/xclcrj596vu73vh/enbconvertor_dx8_dx9_v0035.zip

**Comment by TwelveCharzz** [comment]
Thank you.

**Comment by luke76bg** [comment]
Guys there is a dx8-dx9 converter for silent hill 3 ? Because with dx9 we can play in 3d with tridef, silent hill 2 with generic profile works very well!
